FROM python:2.7.11
ENV PYTHONUNBUFFERED 1
RUN mkdir /cajacochina/
ADD ./requirements.txt /
RUN apt-get update && apt-get install -y libldap2-dev libsasl2-dev
RUN pip install -r /requirements.txt
WORKDIR /cajacochina/